### ISSUE TITLE
Controller-gen binary has bad version

### ISSUE THREAD

**Issue by mogensen** [ob/rules_kubebuilder#7]
First of, great tool!

The only issue I have encountered is that the version of controller-gen included in the bazel rules does not have the correct version set.

See:
![image](https://user-images.githubusercontent.com/592710/139014332-27741f23-1937-48fa-9c5c-9ab2cde385d9.png)

This results in the following annotation on the generated CRDs:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
```

Because of this we can't tell which version is used to generate the different CRDs.
